language: node_js
branches:
    only:
        - master
node_js:
    - '9'
cache:
    directories:
        - node_modules
install:
    - npm install
script:
    - npm run doc
    - bash ./deploy.sh
env:
    global:
        - GH_REF: github.com/compodoc/compodoc-demo-nestjs.git
        - secure: R7Y7snnULZ80EvuzNFaUvpmUPSzv99+KgBsAPqY9nAwWq8Qim/SKOD8+lTTy0ldJoONXWV5QQSIf9pnNOD95p16tttu9d34vIW+om1HyMbj/nnUOQl6kRK8OdbiEesNLH7ohHtKhsXitRf19sZOwvRnTCLpeyJk3Ie5s1y59fM/uzFIHOhYS1ZEVj99gO8fKfPaETiVW5kopaYpma+KugFwIy5tdwTTMjUDucwC43RKERKiDsIh0xjexqhLVpVwYDSAR76qsXlxhgC8cBTDygGD8+bvDI7ifQGXmjK3iHTeV28Mn/y7ako+0SPcAV2jBuk+k0tzWgt/vRJtEJkgrg/k9GKK9+P6G5w8Ugg/2VFWa0qpuvZ1TXGEnkhpcQDEeJjJXBTC5yJ8JkMtJpJxADw0UOD9y1F1xdiNTDULiPAIxqFI1LNuep7aI6c/067Znsdy+3aghLulAzub2DvtW3a9QEt2l9hPRlr76GGsjb0FPE5k6dgoyL00IRvfz2PwGkn8/RkE0UqTGOwEZz8QAH+Fj64W6N1PhxaWgXejOFenGb6U08iKCaIFhiv98zTykois9Hbga65r0bxGaeNRsIElq4Wh5+csFpZVVL3RWZ/tzvWCpWreVke9MhjJQyVG8zJ+EPTM/Jj9BbD2em1nbX4U+csCOpaHixDhf0d3C9RY=
